describe('coverage smoke imports', () => {
  it('loads major component, page, hook, and UI modules', async () => {
    const modules = await Promise.all([
      import('@/components/AddMedication'),
      import('@/components/Calendar'),
      import('@/components/CommandPalette'),
      import('@/components/Communications'),
      import('@/components/ContextMenu'),
      import('@/components/DesktopNotification'),
      import('@/components/DesktopTitleBar'),
      import('@/components/ErrorBoundary'),
      import('@/components/KeyboardShortcutsHelp'),
      import('@/components/KeyboardShortcutsModal'),
      import('@/components/Link'),
      import('@/components/Login'),
      import('@/components/MedicationDetail'),
      import('@/components/MedicationList'),
      import('@/components/MenuBar'),
      import('@/components/MobileKeyboard'),
      import('@/components/NotFound'),
      import('@/components/RefillRequest'),
      import('@/components/Root'),
      import('@/components/Settings'),
      import('@/components/SidePanel'),
      import('@/components/StatusBar'),
      import('@/components/TodayView'),
      import('@/components/Toolbar'),

      import('@/pages/ScreenshotDemo'),
      import('@/pages/TextScalingDemo'),
      import('@/pages/WireframeGenerator'),

      import('@/hooks/useFocusTrap'),
      import('@/hooks/useFormNavigation'),
      import('@/hooks/useKeyboardManager'),
      import('@/hooks/useKeyboardShortcuts'),
      import('@/hooks/useListNavigation'),

      import('@/components/ui/accordion'),
      import('@/components/ui/alert-dialog'),
      import('@/components/ui/alert'),
      import('@/components/ui/aspect-ratio'),
      import('@/components/ui/avatar'),
      import('@/components/ui/badge'),
      import('@/components/ui/breadcrumb'),
      import('@/components/ui/button'),
      import('@/components/ui/calendar'),
      import('@/components/ui/card'),
      import('@/components/ui/carousel'),
      import('@/components/ui/chart'),
      import('@/components/ui/checkbox'),
      import('@/components/ui/collapsible'),
      import('@/components/ui/command'),
      import('@/components/ui/context-menu'),
      import('@/components/ui/dialog'),
      import('@/components/ui/drawer'),
      import('@/components/ui/dropdown-menu'),
      import('@/components/ui/form'),
      import('@/components/ui/hover-card'),
      import('@/components/ui/input'),
      import('@/components/ui/input-otp'),
      import('@/components/ui/label'),
      import('@/components/ui/menubar'),
      import('@/components/ui/navigation-menu'),
      import('@/components/ui/pagination'),
      import('@/components/ui/popover'),
      import('@/components/ui/progress'),
      import('@/components/ui/radio-group'),
      import('@/components/ui/resizable'),
      import('@/components/ui/scroll-area'),
      import('@/components/ui/select'),
      import('@/components/ui/separator'),
      import('@/components/ui/sheet'),
      import('@/components/ui/sidebar'),
      import('@/components/ui/skeleton'),
      import('@/components/ui/slider'),
      import('@/components/ui/sonner'),
      import('@/components/ui/switch'),
      import('@/components/ui/table'),
      import('@/components/ui/tabs'),
      import('@/components/ui/textarea'),
      import('@/components/ui/toggle'),
      import('@/components/ui/toggle-group'),
      import('@/components/ui/tooltip'),
      import('@/components/ui/use-mobile'),
      import('@/components/ui/utils'),

      import('@/context/AppContext'),
      import('@/utils/storage'),
      import('@/App'),
    ]);

    for (const mod of modules) {
      expect(mod).toBeDefined();
      expect(Object.keys(mod).length).toBeGreaterThan(0);
    }
  });
});
